#!/usr/bin/env python3
"""Quantize the embedding and rerank models to 8-bit (affine, group_size=64).

8-bit affine quantization is weight-only symmetric quantization — no calibration
data needed. Uses MLX ``nn.quantize`` on Linear layers (Embedding layers are left
in fp16 to preserve vocabulary fidelity), then saves the quantized parameters in
the standard MLX format that ``mlx_lm.load`` and ``nn.load_weights`` understand.

The output config.json gets a ``quantization`` block so loading code knows the
weights are quantized.

Usage:
    uv run python scripts/quantize_8bit.py <embedding|rerank|both>

Outputs:
    models/jina-embeddings-v5-text-small-retrieval-mlx-8bit/
    models/jinaai/jina-reranker-v3-mlx-8bit/
"""
import argparse
import json
import shutil
import sys
from pathlib import Path

# Allow running from scripts/ without installing the package.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import mlx.core as mx
import mlx.nn as nn
import mlx.nn.utils as nn_utils

PROJECT_DIR = Path(__file__).resolve().parent.parent

EMBED_SRC = PROJECT_DIR / "models" / "jina-embeddings-v5-text-small-retrieval-mlx"
EMBED_DST = PROJECT_DIR / "models" / "jina-embeddings-v5-text-small-retrieval-mlx-8bit"

RERANK_SRC = PROJECT_DIR / "models" / "jinaai" / "jina-reranker-v3-mlx"
RERANK_DST = PROJECT_DIR / "models" / "jinaai" / "jina-reranker-v3-mlx-8bit"

GROUP_SIZE = 64
BITS = 8
QUANT_CONFIG = {"group_size": GROUP_SIZE, "bits": BITS}

# Files that are weight data (regenerated by quantization) or runnable scripts
# (not needed in the quantized copy).
_WEIGHT_OR_SKIP = {"model.safetensors", "projector.safetensors", "model.safetensors.index.json",
                   "rerank.py", "test_examples.py"}


def _linear_only(_path: str, module: nn.Module) -> bool:
    """Quantize only Linear layers; leave Embedding in fp16."""
    return isinstance(module, nn.Linear)


def _copy_metadata(src: Path, dst: Path) -> None:
    for item in src.iterdir():
        if item.name in _WEIGHT_OR_SKIP or item.name in {".cache", "__pycache__"}:
            continue
        target = dst / item.name
        if item.is_file():
            shutil.copy2(item, target)
        elif item.is_dir():
            shutil.copytree(item, target, dirs_exist_ok=True)


def _write_quant_config(dst: Path) -> None:
    cfg_path = dst / "config.json"
    cfg = json.loads(cfg_path.read_text())
    cfg["quantization"] = QUANT_CONFIG
    cfg_path.write_text(json.dumps(cfg, indent=2, ensure_ascii=False))


def _report_size(label: str, src: Path, dst: Path) -> None:
    src_mb = src.stat().st_size / 1e6
    dst_mb = dst.stat().st_size / 1e6
    print(f"  [{label}] {src_mb:.1f} MB -> {dst_mb:.1f} MB ({dst_mb/src_mb*100:.0f}%)")


def quantize_embedding() -> None:
    import importlib.util

    print(f"[embedding] source: {EMBED_SRC}")
    if not (EMBED_SRC / "model.safetensors").exists():
        sys.exit(f"missing {EMBED_SRC/'model.safetensors'}")
    if EMBED_DST.exists():
        shutil.rmtree(EMBED_DST)
    EMBED_DST.mkdir(parents=True)

    spec = importlib.util.spec_from_file_location("jina_mlx_model", EMBED_SRC / "model.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    config = json.loads((EMBED_SRC / "config.json").read_text())
    model = module.JinaEmbeddingModel(config)
    weights = mx.load(str(EMBED_SRC / "model.safetensors"))
    model.load_weights(list(weights.items()))

    print(f"[embedding] quantizing Linear layers -> {BITS}bit/{GROUP_SIZE}group")
    nn.quantize(model, group_size=GROUP_SIZE, bits=BITS, class_predicate=_linear_only)

    params = dict(nn_utils.tree_flatten(model.parameters()))
    mx.save_safetensors(str(EMBED_DST / "model.safetensors"), params)

    _copy_metadata(EMBED_SRC, EMBED_DST)
    _write_quant_config(EMBED_DST)
    _report_size("embedding", EMBED_SRC / "model.safetensors", EMBED_DST / "model.safetensors")
    print(f"[embedding] done -> {EMBED_DST}")


def quantize_rerank() -> None:
    from mlx_lm import load
    from safetensors import safe_open
    from jina_v5_mlx_demo.reranking import MLPProjector

    print(f"[rerank] source: {RERANK_SRC}")
    if RERANK_DST.exists():
        shutil.rmtree(RERANK_DST)
    RERANK_DST.mkdir(parents=True)

    # Backbone via mlx-lm standard load (model_type=qwen3).
    model, _tokenizer = load(str(RERANK_SRC))
    model.eval()
    print(f"[rerank] quantizing backbone Linear layers -> {BITS}bit/{GROUP_SIZE}group")
    nn.quantize(model, group_size=GROUP_SIZE, bits=BITS, class_predicate=_linear_only)
    backbone_params = dict(nn_utils.tree_flatten(model.parameters()))
    mx.save_safetensors(str(RERANK_DST / "model.safetensors"), backbone_params)

    # Projector: build the MLPProjector module, load fp16 weights, quantize via
    # the same nn.quantize path as the backbone so the output is a standard
    # QuantizedLinear-compatible (weight/scales/biases) triple. We must NOT
    # hand-roll mx.quantize + reshape — the packed uint32 format is owned by MLX.
    projector = MLPProjector()
    proj_weights = {}
    with safe_open(str(RERANK_SRC / "projector.safetensors"), framework="numpy") as f:
        for k in f.keys():
            proj_weights[k] = mx.array(f.get_tensor(k))
    projector.load_weights(list(proj_weights.items()))
    print(f"[rerank] quantizing projector -> {BITS}bit/{GROUP_SIZE}group")
    nn.quantize(projector, group_size=GROUP_SIZE, bits=BITS, class_predicate=_linear_only)
    proj_params = dict(nn_utils.tree_flatten(projector.parameters()))
    mx.save_safetensors(str(RERANK_DST / "projector.safetensors"), proj_params)

    _copy_metadata(RERANK_SRC, RERANK_DST)
    _write_quant_config(RERANK_DST)
    _report_size("backbone", RERANK_SRC / "model.safetensors", RERANK_DST / "model.safetensors")
    _report_size("projector", RERANK_SRC / "projector.safetensors", RERANK_DST / "projector.safetensors")
    print(f"[rerank] done -> {RERANK_DST}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("target", choices=["embedding", "rerank", "both"])
    args = parser.parse_args()
    if args.target in ("embedding", "both"):
        quantize_embedding()
    if args.target in ("rerank", "both"):
        quantize_rerank()


if __name__ == "__main__":
    main()
